# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=30 --inject_guidance_every=30 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=20 --inject_guidance_every=20 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=15 --inject_guidance_every=15 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=10 --inject_guidance_every=10 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=6 --inject_guidance_every=6 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=4 --inject_guidance_every=4 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=3 --inject_guidance_every=3 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15
# CUDA_VISIBLE_DEVICES=0 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=2 --inject_guidance_every=2 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15 --selected_sources=32
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 5 5 --selected_sources=32
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 10 10 --selected_sources=32

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15 --selected_sources=64
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 5 5 --selected_sources=64
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 10 10 --selected_sources=64

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 5 15 --selected_sources=128
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 5 5 --selected_sources=128
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 10 10 --selected_sources=128

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 10 15 --selected_sources=32
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 10 10 --selected_sources=32
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 20 20 --selected_sources=32

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 10 15 --selected_sources=64
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 10 10 --selected_sources=64
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 20 20 --selected_sources=64

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 10 15 --selected_sources=128
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 10 10 --selected_sources=128
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 20 20 --selected_sources=128

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 21 21 --selected_sources=32
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 16 16 --selected_sources=32
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 31 31 --selected_sources=32

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 21 21 --selected_sources=64
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 16 16 --selected_sources=64
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 31 31 --selected_sources=64

CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=1 --inject_guidance_every=1 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_overthrust --frequency=5 --num_sources=256 --sigma 21 21 --selected_sources=128
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seg_salt --frequency=6 --num_sources=128 --sigma 16 16 --selected_sources=128
CUDA_VISIBLE_DEVICES=1 python DiffusionModel_2D_FWIGuidedSamplingSynthetic.py --start_guidance_from=700 --guidance_loop=5 --inject_guidance_every=5 --window_size=256 --stride=128 --training_data=seg --num_samples=20 --run_fwi_under=700 --use_fwi=y --resize_model=n --velocity_type=seam_arid --frequency=6 --num_sources=128 --sigma 31 31 --selected_sources=128